FROM welder/bdcs-cli:latest

# tests for bdcs-cli binary
RUN ./tests/test_binary.sh

# depsolve integration tests
ENV START_API_EXTERNALLY 1
RUN ./tests/test_depsolve.sh

# collect binary coverage
RUN mkdir ./dist/hpc/vanilla/tix/bdcs-cli/ && mv bdcs-cli.tix ./dist/hpc/vanilla/tix/bdcs-cli/
