name = "glusterfs"
description = "An example GlusterFS server with samba"

[[modules]]
name = "glusterfs"
version = "3.10.*"

[[modules]]
name = "glusterfs-cli"
version = "3.10.*"

[[packages]]
name = "samba"
version = "4.6.*"
