name = "http-server"
description = "An example http server with PHP and MySQL support."

[[modules]]
name = "httpd"
version = "2.4.*"

[[modules]]
name = "mod_auth_kerb"
version = "5.4"

[[modules]]
name = "mod_ssl"
version = "2.4.*"

[[modules]]
name = "php"
version = "7.1.*"

[[packages]]
name = "tmux"
version = "2.5"

[[packages]]
name = "openssh-server"
version = "7.5*"

[[packages]]
name = "rsync"
version = "3.1.*"
