name = "kubernetes"
description = "An example kubernetes master"

[[modules]]
name = "kubernetes"
version = "1.7.*"

[[modules]]
name = "docker"
version = "1.13.*"

[[modules]]
name = "docker-lvm-plugin"
version = "1.13.*"

[[modules]]
name = "etcd"
version = "3.1.*"

[[modules]]
name = "flannel"
version = "0.7.*"

[[packages]]
name = "oci-systemd-hook"
version = "0.1.*"
